apiVersion: v1
kind: Service
metadata:
  name: {{ include "openzaak.fullname" . }}
  labels:
    {{- include "openzaak.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    {{- include "openzaak.selectorLabels" . | nindent 4 }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "openzaak.nginxFullname" . }}
  labels:
    {{- include "openzaak.nginxLabels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }} : {{ tpl ($value | toString) $ }}
    {{- end }}
  {{- end }}
spec:
  type: {{ .Values.nginx.service.type }}
  ports:
    - port: {{ .Values.nginx.service.port }}
      targetPort: 8080
      name: http
  selector:
    {{- include "openzaak.nginxSelectorLabels" . | nindent 4 }}

