tags:
  redis: true

replicaCount: 1

image:
  repository: openformulieren/open-forms
  pullPolicy: IfNotPresent
  # uses .Chart.AppVersion by default
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podLabels: {}

podSecurityContext:
  fsGroup: 1000

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 1000

livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

readinessProbe:
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

service:
  type: ClusterIP
  port: 80
  annotations: { }

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  className: ""
  # -- ingress hosts
  hosts: []
  #  - host: openformulieren.gemeente.nl
  #    paths:
  #      - path: /
  #        pathType: ImplementationSpecific
  tls: []
  #  - secretName: openforms-tls
  #    hosts:
  #      - openformulieren.gemeente.nl

# -- Specify extra ingresses, for example if you have multiple ingress classes
extraIngress: []
# e.g:
# extraIngress:
#  - name: openformulieren-azuregateway
#    annotations:
#      appgw.ingress.kubernetes.io/ssl-redirect: "true"
#    className: azure-application-gateway
#    hosts:
#      - host: openformulieren.gemeente.nl
#        paths:
#          - path: /
#        pathType: ImplementationSpecific
#        servicename: openformulieren
#        portNumber: 8000
#    tls:
#      - secretName: openformulieren-tls
#        hosts:
#          - "openformulieren.gemeente.nl"

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 1000m
  #   memory: 1Gi
  # requests:
  #   cpu: 250m
  #   memory: 512Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

persistence:
  enabled: true
  size: 1Gi
  storageClassName: ""
  existingClaim: null
  mediaMountSubpath: openforms/media
  privateMediaMountSubpath: openforms/private_media

existingSecret: null

# extraEnvVars Array with extra environment variables to add to openforms
# e.g:
# extraEnvVars:
#   - name: FOO
#     value: "bar"
#
extraEnvVars: []
# extraVolumes Optionally specify extra list of additional volumes
# e.g:
# extraVolumes:
#   - name: verify-certs
#     configMap:
#       name: verify-certs
#
extraVolumes: []
# extraVolumeMounts Optionally specify extra list of additional volumeMounts
# e.g:
# extraVolumeMounts:
#  - name: verify-certs
#    mountPath: /etc/ssl/certs/extra-certs/
extraVolumeMounts: []
# Path to extra certificates or CA (root) certificates, comma seperated
# Wardning, If the file does not exist the pod(s) will not start
# e.g.
# extraVerifyCerts: /etc/ssl/certs/extra-certs/staatdernederlandeng1.pem
extraVerifyCerts: ""

# Extra objects to deploy (value evaluated as a template)
extraDeploy: [ ]

settings:
  djangoSettingsModule: openforms.conf.docker
  allowedHosts: ""
  baseUrl: ""
  useXForwardedHost: false

  # -- Generate secret key at https://djecrety.ir/
  secretKey: ""

  # -- Choises Strict or Lax
  cookieSamesite: ""

  environment: null

  cors:
    # if defining the cors hosts, always include the own URL!
    allowAllOrigins: false
    # allowedOrigins:
    #   - "https://openformulieren.gemeente.nl"
    allowedOrigins: []

  csrf:
    trustedOrigins: []
      # - example.com

  csp:
    reportSave: false
    extraDefaultSrc: []
      # - siteimproveanalytics.com
    extraImgSrc: []
      # - "*.siteimproveanalytics.io"

  throttling:
    enable: true
    rateAnonymous: ""
    rateUser: ""
    ratePolling: ""

  database:
    host: ""
    port: 5432
    name: ""
    username: ""
    password: ""
    sslmode: prefer

  # -- use 2 if enabling ingress
  numProxies: 1

  email:
    host: localhost
    port: 25
    username: ""
    password: ""
    useTLS: false
    defaultFrom: ""

  flower:
    urlPrefix: ""
    basicAuth: ""

  elasticapm:
    url: ""
    token: ""

  sentry:
    dsn: ""

  # Cache settings, when the redis subchart is enabled these settings will be ignored and caching will default to the redis subchart services.
  cache:
    # e.g.:
    # default: openforms-redis-master-0:6379/0
    # axes: openforms-redis-master-0:6379/0
    # portalLocker: openforms-redis-master-0:6379/0
    default: ""
    axes: ""
    portalLocker: ""

  # Celery cache settings, when the redis subchart is enabled these settings will be ignored and caching will default to the redis subchart services
  celery:
    # e.g.:
    # brokerUrl: redis://openforms-redis-master:6379/1
    # resultBackend: redis://openforms-redis-master:6379/1
    brokerUrl: ""
    resultBackend: ""
    logLevel: debug

  isHttps: true

  debug: false

  twoFactorAuthentication:
      # -- Enforce 2 Factor Authentication in the admin or not. Default True. You'll probably want to disable this when using OIDC.
      forceOtpAdmin: true
      # -- Whether to use the 2 Factor Authentication login flow for the admin or not. Default True. You'll probably want to disable this when using OIDC.
      patchAdmin: true

  # -- Configure the maximum allowed file upload size
  maxFileUpload: 50M

  uwsgi:
    master: false
    threads: ""
    processes: ""
    maxRequests: ""
    harakiri: ""

worker:
  replicaCount: 1
  concurrency: 4
  podLabels: {}
  resources: {}
  livenessProbe:
    initialDelaySeconds: 60
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1
  readinessProbe:
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80

nginx:
  image:
    repository: nginxinc/nginx-unprivileged
    pullPolicy: IfNotPresent
    tag: stable
  existingConfigmap: null
  config:
    clientMaxBodySize: 10M
  service:
    type: ClusterIP
    port: 80
  replicaCount: 1
  podLabels: {}
  securityContext:
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: false
    runAsNonRoot: true
    runAsUser: 101
  autoscaling:
    enabled: false
  livenessProbe:
    initialDelaySeconds: 60
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1
  readinessProbe:
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1
  resources: {}

flower:
  enabled: true
  replicaCount: 1
  podLabels: {}
  livenessProbe:
    initialDelaySeconds: 60
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  readinessProbe:
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  resources: {}

beat:
  enabled: true
  replicaCount: 1
  podLabels: {}
  livenessProbe:
    initialDelaySeconds: 60
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  readinessProbe:
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  resources: {}

##################
# Redis subchart #
##################

redis:
  architecture: standalone
  auth:
    enabled: false
  master:
    persistence:
      enabled: false
    resources:
      requests:
        cpu: 10m
        memory: 20Mi
