apiVersion: v1
kind: Service
metadata:
  name: {{ include "openforms.fullname" . }}
  labels:
    {{- include "openforms.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    {{- include "openforms.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "openforms.nginxFullname" . }}
  labels:
    {{- include "openforms.nginxLabels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }} : {{ tpl ($value | toString) $ }}
    {{- end }}
  {{- end }}
spec:
  type: {{ .Values.nginx.service.type }}
  ports:
    - port: {{ .Values.nginx.service.port }}
      targetPort: 8080
      name: http
  selector:
    {{- include "openforms.nginxSelectorLabels" . | nindent 4 }}
