tags:
  redis: true
  rabbitmq: true

replicaCount: 1

image:
  repository: openzaak/open-notificaties
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podLabels: {}

podSecurityContext:
  fsGroup: 1000

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 1000

livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

readinessProbe:
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  className: ""
  # -- ingress hosts
  hosts: []
  #  - host: opennotificaties.gemeente.nl
  #    paths:
  #      - path: /
  #        pathType: ImplementationSpecific
  tls: []
  #  - secretName: opennotificaties-tls
  #    hosts:
  #      - opennotificaties.gemeente.nl

# -- Specify extra ingresses, for example if you have multiple ingress classes
extraIngress: []
# e.g:
# extraIngress:
#  - name: opennotificaties-azuregateway
#    annotations:
#      appgw.ingress.kubernetes.io/ssl-redirect: "true"
#    className: azure-application-gateway
#    hosts:
#      - host: opennotificaties.gemeente.nl
#        paths:
#          - path: /
#        pathType: ImplementationSpecific
#        servicename: opennotificaties
#        portNumber: 8000
#    tls:
#      - secretName: opennotificaties-tls
#        hosts:
#          - "opennotificaties.gemeente.nl"

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 200m
  #   memory: 256Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

existingSecret: null

# -- Array with extra environment variables to add
extraEnvVars: []
# e.g:
# extraEnvVars:
#   - name: FOO
#     value: "bar"

# -- Optionally specify extra list of additional volumes
extraVolumes: []
# e.g:
# extraVolumes:
#   - name: verify-certs
#     configMap:
#       name: verify-certs

# -- Optionally specify extra list of additional volumeMounts
extraVolumeMounts: []
# e.g:
# extraVolumeMounts:
#  - name: verify-certs
#    mountPath: /etc/ssl/certs/extra-certs/

# -- Path to extra certificates or CA (root) certificates, comma seperated
# Warning, If the file does not exist the pod(s) will not start
extraVerifyCerts: ""
# e.g.
# extraVerifyCerts: /etc/ssl/certs/extra-certs/staatdernederlandeng1.pem

settings:
  allowedHosts: ""
  djangoSettingsModule: nrc.conf.docker
  useXForwardedHost: true

  # -- When set to true notifications are saved to the database and accessible from the admin interface
  logNotifications: true

  # -- Generate secret key at https://djecrety.ir/
  secretKey: ""

  # -- sets the 'ENVIRONMENT' variable
  environment: ""

  database:
    host: ""
    port: 5432
    username: ""
    password: ""
    name: ""
    sslmode: prefer

  # -- use 2 if enabling ingress
  numProxies: 1

  email:
    host: localhost
    port: 25
    username: ""
    password: ""
    useTLS: false

  flower:
    urlPrefix: ""
    basicAuth: ""

  elasticapm:
    url: ""
    token: ""
    serviceName: ""

  sentry:
    dsn: ""

  cache:
    # -- Sets 'CACHE_DEFAULT' var, only required when tags.redis is false
    default: ""
    # -- Sets 'CACHE_AXES' var, only required when tags.redis is false
    axes: ""
    # When not using the redis subcharts you can set them manually like this:
    # default: myredisserver:6379/0
    # axes: myredisserver:6379/0

  celery:
    # -- Celery loglevel
    logLevel: debug
    # -- Sets the 'CELERY_BROKER_URL' var, only required when tags.rabbitmq is false
    brokerUrl: ""
    # -- Sets the 'CELERY_RESULT_BACKEND' var, only required when tags.redis is false
    resultBackend: ""
    # -- Sets the 'PUBLISHER_BROKER_URL' var, only required when tags.rabbitmq is false
    publishBrokerUrl: ""
    # -- RabbitMQ server hostname
    rabbitmqHost: ""
    # When not using the rabbitmq / redis subcharts you can set them manually like this:
    #
    # brokerUrl: amqp://username:password@myrabbitmqbroker:5672//
    # resultBackend: redis://myredisserver:6379/1
    # publishBrokerUrl: amqp://username:password@myrabbitmqbroker::5672/%2F
    # rabbitmqHost: myrabbitmqbroker

  isHttps: true

  debug: false

  uwsgi:
    master: ''
    threads: ''
    processes: ''
    maxRequests: ''
    harakiri: ''

worker:
  replicaCount: 1
  concurrency: 4
  podLabels: {}
  resources: {}
  livenessProbe:
    initialDelaySeconds: 60
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1
  readinessProbe:
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80

flower:
  enabled: true
  replicaCount: 1
  podLabels: {}
  livenessProbe:
    initialDelaySeconds: 60
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  readinessProbe:
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  resources: {}

##################
# Redis subchart #
##################

redis:
  architecture: standalone
  auth:
    enabled: false
  master:
    persistence:
      enabled: false
    resources:
      requests:
        cpu: 10m
        memory: 20Mi

#####################
# RabbitMQ subchart #
#####################

rabbitmq:
  auth:
    username: user
    password: ""
    erlangCookie: ""

  persistence:
    enabled: false
    size: 1Gi
    existingClaim: null